In [4]:
import multiprocessing
import time
import serial
import csv
import numpy as np


def datacol(conn):

    ser = serial.Serial('COM9', 9600)  # Replace with the correct port name

    start_time=time.time()

    for i in range(10):
        line = ser.readline().decode().strip()
        #print(line)
        values = line.split(',')
        if len(values) != 6:
            continue
        try:
            accel_x = float(values[0])
            accel_y = float(values[1])
            accel_z = float(values[2])
            gyro_x = float(values[3])
            gyro_y = float(values[4])
            gyro_z = float(values[5])
        except ValueError:
            continue

        row=[accel_x, accel_y, accel_z, gyro_x, gyro_y, gyro_z]

        conn.send(row)
        print("Sent the message: {}".format(row))
        #time.sleep(0.5)

    end_time = time.time()
    dt=end_time - start_time
    print("DT:", dt)
        
    conn.close()

    ser.close()
    
    
    
    
    
    
    
    
    
    
    
    

def receiver(conn):
    """
    function to print the messages received from other
    end of pipe
    """
    arr=np.array([[]])
    
    while 1:
        rec = conn.recv()
        if rec == "END":
            break
        #
        print("Received the message: {}".format(rec))
        print(type(rec))
        arr=np.vstack([arr, np.array(rec)])
        print(arr)


        
        
        
        
        
        
        
        
        
        
        
#####################################################################################################       
if __name__ == "__main__":
    # messages to be sent
    #msgs = ["hello", "hey", "hru?", "END"]

    # creating a pipe
    parent_conn, child_conn = multiprocessing.Pipe()

    # creating new processes
    p1 = multiprocessing.Process(target=datacol, args=(parent_conn,	))
    p2 = multiprocessing.Process(target=receiver, args=(child_conn,))

    # running processes
    p1.start()
    p2.start()

    # wait until processes finish
    p1.join()
    p2.join()

In [2]:
sd=[]
type(sd)

list

In [26]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
#nrow=np.array([7,8,9])
arr=np.vstack([arr, np.array([7,8,9])])
#arr=np.append(arr,[[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr = np.empty((0, 6))

# print the array
print(arr)

[]


In [29]:
arr=np.vstack([arr, np.array([7,8,9,1,2,3])])

In [30]:
arr

array([[7., 8., 9., 1., 2., 3.]])

In [41]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [32]:
arr = np.empty((0, 6))
arr = arr[8:, :]
arr

array([], shape=(0, 6), dtype=float64)

In [33]:
arr = np.random.rand(15, 6)


In [34]:
arr

array([[0.26621639, 0.23438992, 0.23590034, 0.99010489, 0.58307059,
        0.01597098],
       [0.22032089, 0.05964689, 0.81769736, 0.86670051, 0.60333227,
        0.58839881],
       [0.10497556, 0.85690388, 0.59519345, 0.13498943, 0.39756232,
        0.26697664],
       [0.36638905, 0.13882981, 0.2891582 , 0.3025807 , 0.73649399,
        0.31216652],
       [0.16067524, 0.30780466, 0.34401037, 0.72164904, 0.33673015,
        0.60599332],
       [0.44423146, 0.20799117, 0.28674947, 0.1526426 , 0.22933455,
        0.56250981],
       [0.21398791, 0.3554156 , 0.14422795, 0.36444818, 0.18811083,
        0.60335938],
       [0.54882337, 0.59607227, 0.55267355, 0.38393779, 0.90699902,
        0.65964253],
       [0.53790698, 0.76262732, 0.56688023, 0.95719041, 0.470639  ,
        0.46595874],
       [0.567721  , 0.40038367, 0.33118562, 0.25662508, 0.1045202 ,
        0.17350738],
       [0.75137958, 0.16451721, 0.84200578, 0.71419197, 0.64391926,
        0.18942887],
       [0.66338894, 0

In [35]:
        arr = arr[8:, :]

In [36]:
arr

array([[0.53790698, 0.76262732, 0.56688023, 0.95719041, 0.470639  ,
        0.46595874],
       [0.567721  , 0.40038367, 0.33118562, 0.25662508, 0.1045202 ,
        0.17350738],
       [0.75137958, 0.16451721, 0.84200578, 0.71419197, 0.64391926,
        0.18942887],
       [0.66338894, 0.44279095, 0.54667469, 0.41768113, 0.57151496,
        0.90152195],
       [0.80150856, 0.05184668, 0.01526065, 0.20418476, 0.60330661,
        0.78974793],
       [0.5334051 , 0.22816826, 0.56012249, 0.31743427, 0.67271252,
        0.86145265],
       [0.9352543 , 0.80196779, 0.60132321, 0.95762775, 0.53143201,
        0.73504116]])

In [48]:
import pandas as pd

# Create a DataFrame with three columns
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})


# Access the first column using .iloc[]
df.iloc[:, 2]


0    7
1    8
2    9
Name: C, dtype: int64